AWSTemplateFormatVersion: '2010-09-09'
Description: 'Census Data ETL - PostgreSQL RDS Instance'

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: census-data-db
    Description: Database instance identifier
  
  DBName:
    Type: String
    Default: census_data
    Description: Database name
  
  DBUsername:
    Type: String
    Default: census_user
    Description: Database master username
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database master password
    MinLength: 8
  
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: Database instance class
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
  
  AllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage in GB
    MinValue: 20
    MaxValue: 65536
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the RDS instance will be created
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for the RDS subnet group

Resources:
  # Security Group for RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Census Data RDS instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: PostgreSQL access from anywhere (consider restricting this in production)
  
  # Subnet Group for RDS
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Census Data RDS instance
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${DBInstanceIdentifier}-subnet-group'
  
  # RDS PostgreSQL Instance
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '14.7'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      DBSubnetGroupName: !Ref RDSSubnetGroup
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: true
      StorageEncrypted: true
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Ref DBInstanceIdentifier
        - Key: Project
          Value: Census-Data-ETL
        - Key: Environment
          Value: Development

Outputs:
  DBEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DBEndpoint'
  
  DBPort:
    Description: RDS instance port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DBPort'
  
  DBName:
    Description: Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${AWS::StackName}-DBName'
  
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId' 